### ISSUE TITLE
UICollectionViewCell Reuse Issue

### ISSUE THREAD

**Issue by inPhilly** [SDWebImage/SDWebImageLinkPlugin#1]
When `sd_setImageFromURL`: is used to set a `UIImageView`'s image in a `UICollectionView` cell, and a `UICollectionView`, once populated, is scrolled quickly up and down, the images appear and disappear while scrolling. I believe that this may be a `UICollectionViewCell` `prepareForReuse` issue, and that `sd_cancelCurrentImageLoad` is not working properly for this plugin.

**Comment by dreampiggy** [comment]
Try version [0.2.0](https://github.com/SDWebImage/SDWebImageLinkPlugin/releases/tag/0.2.0), which supports caching `LPLinkMetadata`, actually the first usable version.

**Comment by inPhilly** [comment]
I assume this is working now since the version has been updated, and I am using LPLinkView instead of UIImageView in any case. Thank you.
