### ISSUE TITLE
Framework "not safe" for App Extensions

### ISSUE THREAD

**Issue by inPhilly** [SDWebImage/SDWebImageLinkPlugin#11]
I am building this framework with Carthage and everything seems to be working until I run the App Extension, which includes SDWebImageLinkPlugin.

When I run the App Extension, I get this warning message:

> Linking against a dylib which is not safe for use in application extensions: ...MyApp/Carthage/Build/iOS/SDWebImageLinkPlugin.framework/SDWebImageLinkPlugin

**Comment by dreampiggy** [comment]
This framework does not designed to use in App Extension, actually...Did you use Link Plugin in Notification or Siri Extension App ?

**Comment by dreampiggy** [comment]
Seems this is just a warning cause by `APPLICATION_EXTENSION_API_ONLY` build setting. We set it to NO.

Does this cause any runtime issue ? If not, maybe we can just ignore this. Or if you really want this, I can update the build settings.

**Comment by inPhilly** [comment]
I am using this in an Action Extension:
https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Action.html

Although I can't see if it causes runtime issues, I wouldn't want to include it in a live app if it were deemed 'unsafe' by the warnings.

I have APPLICATION_EXTENSION_API_ONLY set to YES and probably need it to stay that way. Is there something that is making this unsafe for Action Extensions? Can it be changed?

**Comment by inPhilly** [comment]
By the way, I am using version 0.2.3. I get this warning both:
1. when I install the plugin via Carthage, and
2. when I manually include all of the files, including the SDWebImageLinkPlugin.h file
Currently, I am manually including all of the files, but since you added the shouldfetchVideoResources option, I will probably go back to Carthage. In either case, though, this error occurs, so it really doesn't make a difference on your end which method I am using. Also, changing a build setting on your end will likely not fix this, since I do get this error when I am simply manually including the files.

**Comment by inPhilly** [comment]
Updating this setting seems like it may make the difference. I would appreciate if you could update the Build Settings. Thank you.

**Comment by dreampiggy** [comment]
Should be solved by [0.3.0 version](https://github.com/SDWebImage/SDWebImageLinkPlugin/releases/tag/0.3.0)
