### ISSUE TITLE
Can SDImageCacheType be changed from SDImageCacheTypeNone?

### ISSUE THREAD

**Issue by inPhilly** [SDWebImage/SDWebImageLinkPlugin#2]
When I use `SDWebImage` to load a `UIImage` from a typical image `NSURL`, the results are automatically cached. Using SDWebImageLinkPlugin, I set a `UIImageView`'s image in a `UICollectionViewCell` using `sd_setImageWithURL`; after the controller fully loads, I exit the controller, come back, and everything has to reload from the beginning. Nothing is retrieved from the `SDImageCache` and in fact the `SDImageCacheType` is `SDImageCacheTypeNone`. Is this the expected behavior? Is there a way I can change this behavior to mimic that of the default `NSURL` loader?

**Comment by dreampiggy** [comment]
@inPhilly  The `SDWebImageStoreCacheType` context option is provided by user, this framework does not set anything.

Try version [0.2.0](https://github.com/SDWebImage/SDWebImageLinkPlugin/releases/tag/0.2.0), which supports caching `LPLinkMetadata`, actually the first usable version.
