### ISSUE TITLE
UICollectionViewDataSourcePrefetching

### ISSUE THREAD

**Issue by inPhilly** [SDWebImage/SDWebImageLinkPlugin#8]
I would like to do some prefetching of data to help mitigate the situation where no LPLinkMetadata has been cached for a UICollectionView with many cells. Is there any way to prefetch LPLinkMetadata using this framework?

**Comment by dreampiggy** [comment]
You can use prefetching, this framework just works as SDWebImage for normal URL, no extra huge behavior between the design.
