### ISSUE TITLE
Way to specify custom LPLinkMetadata for when it can't be fetched?

### ISSUE THREAD

**Issue by inPhilly** [SDWebImage/SDWebImageLinkPlugin#9]
Is there a way, with this framework plugin, to specify custom LPLinkMetadata for when it is unable to be fetched by LPMetadataProvider?

**Comment by dreampiggy** [comment]
Use the `SDWebImageContextLinkMetadata` context option, which will use that instead of self-fetched metadata and set to `LPLinkView`

**Comment by dreampiggy** [comment]
See: https://github.com/SDWebImage/SDWebImageLinkPlugin/blob/0.2.3/SDWebImageLinkPlugin/Classes/LPLinkView+WebCache.m#L89-L92
